# Generated by Django 5.1.7 on 2025-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_user_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
