# Generated by Django 5.1.7 on 2025-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_address_line_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
